### ISSUE TITLE
gpg: error reading key: No public key :(

### ISSUE THREAD

**Issue by CLJP85** [rifsxd/kittyfetch#2]
It won't fetch the PGP key whenever I try to download :(
![Screenshot From 2024-10-13 16-10-47](https://github.com/user-attachments/assets/ccbf4b25-c400-435a-bd5c-bf261baf867e)

**Comment by rifsxd** [comment]
validpgpkeys=(
	'SKIP'
)

Remove this part in MAKEPKG file of the aur package

**Comment by rifsxd** [comment]
Or just clone this repo and cd to src directory and run makepkg -si

**Comment by rifsxd** [comment]
If you are still facing issues I would suggest install blazefetch instead cuz kittyfetch is built-in for that

**Comment by CLJP85** [comment]
> validpgpkeys=( 'SKIP' )
> 
> Remove this part in MAKEPKG file of the aur package

Ty!

**Comment by CLJP85** [comment]
> Or just clone this repo and cd to src directory and run makepkg -si

I will consider this

**Comment by CLJP85** [comment]
> If you are still facing issues I would suggest install blazefetch instead cuz kittyfetch is built-in for that

kittyfetch in its entirety...?  within the blazefetch package?  I have fastfetch - i had* neofetch but currently fastfetch i believe...  I dont remember but fetch's*  like theres a hand full of similar type packages -  i think i recall conflicting when trying multiple variants - I can always un/install switch em out as I feel need for a change tho - ill check blazefetch out ty sir ^^;
